### ISSUE TITLE
pandas.errors.ParserError: Error tokenizing data. C error: out of memory

### ISSUE THREAD

**Issue by svburke** [mzabrams/fars-cleaner#1]
While running the example command given here:

```
from fars_cleaner import FARSFetcher, load_pipeline

fetcher = FARSFetcher(project_dir=SOME_PATH)
vehicles, accidents, people = load_pipeline(fetcher=fetcher,
                                            first_run=True,
                                            target_folder=SOME_PATH)
```

I am getting an error on one of my machines (Windows 10 16Gb RAM):

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\svbur\AppData\Local\Programs\Python\Python38-32\lib\site-packages\fars_cleaner\data_loader.py", line 128, in load_pipeline
    vehicle, person, accident = load_basic(year,
  File "C:\Users\svbur\AppData\Local\Programs\Python\Python38-32\lib\site-packages\fars_cleaner\data_loader.py", line 523, in load_basic
    veh_df = pd.read_csv(vehicle_file,
  File "C:\Users\svbur\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\svbur\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\parsers\readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\svbur\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\parsers\readers.py", line 581, in _read
    return parser.read(nrows)
  File "C:\Users\svbur\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\parsers\readers.py", line 1255, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "C:\Users\svbur\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 230, in read
    data = self._reader.read(nrows)
  File "pandas\_libs\parsers.pyx", line 787, in pandas._libs.parsers.TextReader.read
  File "pandas\_libs\parsers.pyx", line 876, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 1960, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: out of memory
```

I was able to successfully run this on a different machine, (MacOS Monterey 12.5.1, 16 Gb RAM). 

I think it would be worth looking into a way to read in and handle the data in a less memory intense way.

**Comment by mzabrams** [comment]
Interesting -- not sure why that would throwing an out of memory error on Windows only, I'll look into that

**Comment by mzabrams** [comment]
@svburke Would you be able to rerun this with the debug flag set to 2 in `load_pipeline()`, and post the result with how many years are loaded prior to the out of memory error?

**Comment by svburke** [comment]
@mzabrams, here is the first output from the load_pipeline() with the debug=2 flag:

```
Fetched originals, loading to pandas....
1975
1976
1977
1978

Traceback (most recent call last):
File "<stdin>", line 1, in <module>
 File "C:\Users\svbur\AppData\Local\Programs\Python\Python38-32\lib\site-packages\fars_cleaner\data_loader.py", line 128, in load_pipeline
 vehicle, person, accident = load_basic(year,
  File "C:\Users\svbur\AppData\Local\Programs\Python\Python38-32\lib\site-packages\fars_cleaner\data_loader.py", line 531, in load_basic
per_df = pd.read_csv(person_file, encoding='cp1252',
  File "C:\Users\svbur\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
return func(*args, **kwargs)
  File "C:\Users\svbur\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\parsers\readers.py", line 680, in read_csv
 return _read(filepath_or_buffer, kwds)
File "C:\Users\svbur\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\parsers\readers.py", line 581, in _read
return parser.read(nrows)
 File "C:\Users\svbur\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\parsers\readers.py", line 1255, in read
index, columns, col_dict = self._engine.read(nrows)
   File "C:\Users\svbur\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 230, in read
data = self._reader.read(nrows)
   File "pandas\_libs\parsers.pyx", line 787, in pandas._libs.parsers.TextReader.read
  File "pandas\_libs\parsers.pyx", line 876, in pandas._libs.parsers.TextReader._read_rows
File "pandas\_libs\parsers.pyx", line 1960, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: out of memory 
```

I tried running it a few more times, and it would then crash on 1977. Same error output still.

**Comment by mzabrams** [comment]
I've made some progress on reducing memory overhead on a 16GB Windows 10 VM, but haven't been able to fully execute this program under those specifications. Work in progress, but may require a note in the README on system requirement limitations for the time being.

**Comment by mzabrams** [comment]
Closing this as "won't fix" -- this seems to be OS dependent and I've been unsuccessful in fixing this issue to date. A note has been added to the README regarding this issue.
